version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db_data:/data

volumes:
  db_data:
